### ISSUE TITLE
Move to minetest-mods

### ISSUE THREAD

**Issue by Panquesito7** [minetest-mods/teleport-request#18]
It would be great to see this mod in [`minetest-mods`](https://github.com/minetest-mods).
IMHO, it would be much more maintained.

Users will be able to find this repository easier, too.

**Comment by ChaosWormz** [comment]
On it

**Comment by Panquesito7** [comment]
If you need or want more information, click [this](https://minetest-mods.github.io) link. 🙂

**Comment by ChaosWormz** [comment]
Panquesito7, i  barely know how to code (and that's putting it midly) it's very bad idea to put me as the main maintainer. I highly suggest using forwarding a fork instead. this repo only existed in the first place due to a request by server admin.

So if this is to go on minetest-mods it's either be a fork  or a transfer ownership to you, or someone else who can do lua magic.

**Comment by Panquesito7** [comment]
> it's very bad idea to put me as the main maintainer

You and I can be the main maintainers if you wish.

> transfer ownership to you

This is up to you, because you own the repository.

It's not necessary to move this to `minetest-mods`, but I thought it would be a good idea.
We can keep you as the owner and close this issue. 🙂

**Comment by Panquesito7** [comment]
@ChaosWormz I still think this would be a good idea. Let's keep us both as the maintainers. If there's a new PR made or a new issue I will review it as soon as I can. What do you think? 🙂

**Comment by ChaosWormz** [comment]
I agree.

**Comment by Panquesito7** [comment]
If you want you can transfer ownership to me then I'll start the process to transfer it to Minetest Mods.

Thank you. 🙂

**Comment by ChaosWormz** [comment]
would that break links?

**Comment by Panquesito7** [comment]
No, it will be automatically redirected. 🙂

**Comment by ChaosWormz** [comment]
i get warning: Panquesito7/teleport-request already exists

**Comment by Panquesito7** [comment]
Ah, let me fix that. Give me 5 minutes. Sorry for that.

**Comment by Panquesito7** [comment]
Try doing the transfer again. 🙂
Thank you.

**Comment by ChaosWormz** [comment]
Still getting the same error

**Comment by Panquesito7** [comment]
Try doing it again. Sorry for the inconvenience. Thank you. 🙂

**Comment by Panquesito7** [comment]
Thanks for transferring the repository. I will work on this now. 🙂

**Comment by Panquesito7** [comment]
https://github.com/minetest-mods/minetest-mods.github.io/issues/107
